### ISSUE TITLE
Fix frontend to run using yarn

### ISSUE THREAD

**Issue by Hasteerp** [activist-org/activist#1021]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](.github/CODE_OF_CONDUCT.md)

### Behavior

_Current Behavior:_

When you follow the steps under [Contributing.md](https://github.com/activist-org/activist/blob/main/CONTRIBUTING.md#dev-env) to **run frontend using Yarn**. It gives the following error. 
<img width="748" alt="Screenshot 2024-11-25 at 10 09 11 AM" src="https://github.com/user-attachments/assets/965e3a94-8330-4e89-a9e4-60e169fba2c1">

The error suggests too many open files. Possible error is too many file watchers. 

_Expected Behavior:_

Frontend should run locally using yarn. It should run without file watchers or an option to turn off these file watchers when trying to run locally. It should not try to open watchers in `node_modules`.

**Comment by andrewtavis** [comment]
Thanks a lot for this issue, @Hasteerp! Would you have interest in looking in to this? We can also save it till you're done with the other issue.

**Comment by Hasteerp** [comment]
Sure @andrewtavis , I would be happy to take this up once I am done working on the other issue. 
But feel free to assign it to someone else if someone shows interest :)

**Comment by cquinn540** [comment]
Found what I think is the root cause: https://github.com/nuxt/nuxt/issues/29744

I tried changing `package.json` to include:
```json
  "resolutions": {
    "chokidar": "3.6.0",
    "playwright-core": "1.45.1"
  }
```

Reran `yarn install` I can start the frontend locally now.  Can't fully test it because my backend keeps crashing:
```
django_backend  | Traceback (most recent call last):
django_backend  |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
django_backend  |     return self.cursor.execute(sql, params)
django_backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django_backend  | psycopg2.errors.UndefinedTable: relation "entities_groupfaq" does not exist
django_backend  | LINE 1: DELETE FROM "entities_groupfaq" WHERE "entities_groupfaq"."g...
django_backend  |                     ^
django_backend  |
django_backend  |
django_backend  | The above exception was the direct cause of the following exception:
django_backend  |
django_backend  | Traceback (most recent call last):
django_backend  |   File "/app/manage.py", line 27, in <module>
django_backend  |     main()
django_backend  |   File "/app/manage.py", line 23, in main
django_backend  |     execute_from_command_line(sys.argv)
django_backend  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
django_backend  |     utility.execute()
django_backend  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
django_backend  |     self.fetch_command(subcommand).run_from_argv(self.argv)
django_backend  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 413, in run_from_argv
django_backend  |     self.execute(*args, **cmd_options)
django_backend  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 459, in execute
django_backend  |     output = self.handle(*args, **options)
django_backend  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django_backend  |   File "/app/backend/management/commands/populate_db.py", line 45, in handle
django_backend  |     UserModel.objects.exclude(username="admin").delete()
django_backend  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1188, in delete
django_backend  |     deleted, _rows_count = collector.delete()
django_backend  |                            ^^^^^^^^^^^^^^^^^^
django_backend  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/deletion.py", line 472, in delete
django_backend  |     count = qs._raw_delete(using=self.using)
django_backend  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django_backend  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1210, in _raw_delete
django_backend  |     cursor = query.get_compiler(using).execute_sql(CURSOR)
django_backend  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django_backend  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
django_backend  |     cursor.execute(sql, params)
django_backend  |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 122, in execute
django_backend  |     return super().execute(sql, params)
django_backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django_backend  |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
django_backend  |     return self._execute_with_wrappers(
django_backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django_backend  |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
django_backend  |     return executor(sql, params, many, context)
django_backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django_backend  |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
django_backend  |     with self.db.wrap_database_errors:
django_backend  |   File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
django_backend  |     raise dj_exc_value.with_traceback(traceback) from exc_value
django_backend  |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
django_backend  |     return self.cursor.execute(sql, params)
django_backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by cquinn540** [comment]
destroying and recreating my environment with `docker-compose rm -f -v --env-file .env.dev` fixed the database issue I ran into

**Comment by andrewtavis** [comment]
Do you think anything else is needed here, @cquinn540?

**Comment by cquinn540** [comment]
There is still the trouble caused by the local env and container env sharing the same `node_modules`.  The right way to fix it IMO is that big directory structure change I mentioned when we were talking with Matt, but there is a potential workaround:

https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder

**Comment by andrewtavis** [comment]
Closing this as I just checked `yarn run dev` in the frontend and there are no issues :) This likely was fixed with us updating Yarn 😊

Hope all are well!
